# Generated by Django 6.0.6 on 2026-06-04 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee'), ('driver', 'Driver'), ('not assigned', 'Not Assigned')], default='not assigned', max_length=20)),
                ('role_approved', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['super admin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to='accounts.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
