# Generated by Django 6.0.6 on 2026-06-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch'),
        ),
    ]
